name: earthguard
description: Complete Earthquake Response System

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core sensors and location
  sensors_plus: ^3.0.1
  geolocator: ^9.0.2
  
  # Database
  sqflite: ^2.3.0
  
  # Networking
  http: ^1.1.0
  
  # Utilities
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true